MeController Refactor
osu-tournament-rating/otr-api pull request #213
Opened 2024-03-18 16:37 UTC by myssto

Refactor of the me controller and related services pursuant to #207

Breaking changes:
- UserInfoDTO changes
  - Remove `UserId` field
  - Change `Id` field to use o!TR id instead of osu! id
  - Rename `Roles` field to `Scopes`

2024-03-18 21:26 UTC, hburn7 requested changes
There's a lot of confusion with how the different ids work together. Will re-review after these comments are addressed.

2024-03-18 21:26 UTC, hburn7 commented on API/DTOs/UserInfoDTO.cs
> +    public int Id { get; set; }
This class does need a `PlayerId` field as well, that's what `Id` was before.

2024-03-18 21:26 UTC, hburn7 commented on API/Repositories/Implementations/UserRepository.cs
> +    public async Task<User?> GetByOsuIdAsync(int osuId) =>
`osuId` should always be passed as `long`, make sure this is being done everywhere.

2024-03-18 21:26 UTC, hburn7 commented on API/Services/Implementations/UserService.cs
This doesn't make sense. The `playerId` is not the same as `osuId`.

2024-03-18 21:46 UTC, myssto commented
Yep I definitely managed to confuse myself along the way here, will give it another go through

2024-03-22 20:42 UTC, myssto commented
Should have taken care of the type miss-matching stuff. If you could scrutinize this one a little more than usual for me because I can't seem to find any refactoring errors anymore, but I just want to be 100%

2024-03-25 20:08 UTC, hburn7 approved these changes

2024-03-26 14:05 UTC, hburn7 commented
Awaiting approval before merge:

- [ ] https://github.com/osu-tournament-rating/otr-web/pull/144

2024-03-27 19:41 UTC, merged