Add screening API
osu-tournament-rating/otr-api pull request #220
Opened 2024-03-23 22:02 UTC by hburn7

Adds the screening API as described in #211 (no tests, waiting on #219 before adding them).

Have tested locally, all seems fine. This is a relatively simple feature addition.

Example request:
```bash
curl -X 'POST' \
  'http://localhost:5075/api/v1/screening' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "ruleset": 0,
  "minRating": 500,
  "maxRating": 1200,
  "allowProvisional": false,
  "tournamentsPlayed": 3,
  "peakRating": 1600,
  "matchesPlayed": 8,
  "osuPlayerIds": [
    8191845,
    1234,
    12408961,
    7516954
  ]
}'
```

Example response:
```json
[
  {
    "playerId": 440,
    "username": "Stage",
    "osuPlayerId": 8191845,
    "screeningResult": 0,
    "screeningFailReason": 0,
    "resultMessage": "Pass",
    "failReason": "None"
  },
  {
    "playerId": null,
    "username": null,
    "osuPlayerId": 1234,
    "screeningResult": 1,
    "screeningFailReason": 1,
    "resultMessage": "Fail",
    "failReason": "NoData"
  },
  {
    "playerId": 4285,
    "username": "maliszewski",
    "osuPlayerId": 12408961,
    "screeningResult": 1,
    "screeningFailReason": 36,
    "resultMessage": "Fail",
    "failReason": "MaxRating, PeakRatingTooHigh"
  },
  {
    "playerId": 4649,
    "username": "ZephyrCo",
    "osuPlayerId": 7516954,
    "screeningResult": 1,
    "screeningFailReason": 2,
    "resultMessage": "Fail",
    "failReason": "MinRating"
  }
]
```

2024-03-25 06:21 UTC, hburn7 commented
Actually, I want to change "failReason" to "failReasonMessage" in the response.

2024-03-27 21:25 UTC, myssto requested changes

2024-03-27 21:25 UTC, myssto commented on API/Controllers/ScreeningController.cs
> +[EnableCors]
```suggestion
```
EnableCors attribute not needed on controller level when using global policy

2024-03-27 21:48 UTC, hburn7 commented on API/Controllers/ScreeningController.cs
> +    public async Task<Results<Ok<IEnumerable<ScreeningResultDTO>>, BadRequest<string>>> ScreenAsync([FromBody] ScreeningDTO screeningRequest)
Return to IActionResult format

2024-03-27 21:55 UTC, myssto commented
<@146092837723832320>

2024-04-02 01:19 UTC, hburn7 commented on API/Controllers/ScreeningController.cs
> +        screeningRequest.OsuPlayerIds = screeningRequest.OsuPlayerIds.Distinct();
I think it's better to not reject if a user submits duplicates when it basically costs us nothing to filter it out. The alternative is the user has to filter through hundreds of ids to remove a few duplicates.

2024-04-02 01:21 UTC, myssto commented on API/Controllers/ScreeningController.cs
> +        screeningRequest.OsuPlayerIds = screeningRequest.OsuPlayerIds.Distinct();
Ah yeah, you're right. If we did something like this it would reject just like any other model state error

2024-04-02 01:23 UTC, hburn7 commented on API/Services/Implementations/ScreeningService.cs
> +        if (idList.Count == 0)
`.Count == 0` is apparently better for performance https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1860

2024-04-02 01:24 UTC, hburn7 commented on API/Services/Implementations/ScreeningService.cs
> +        if (idList.Count == 0)
Up to you on whether this is important, I have no preference.

2024-04-02 01:26 UTC, myssto commented on API/Services/Implementations/ScreeningService.cs
> +        if (idList.Count == 0)
Nah, not important. If that is more performant then we should do that

2024-04-04 03:27 UTC, myssto requested changes

2024-04-04 03:27 UTC, myssto commented on API/Services/Implementations/ScreeningService.cs
> +        return dto;
```suggestion
        return new ScreeningResultDTO
        {
            PlayersPassed = passed,
            PlayersFailed = failed,
            ScreeningResults = resultCollection
        };
```

2024-04-04 03:27 UTC, myssto commented on API/Services/Implementations/ScreeningService.cs
> +        var peakRating = await playerStatsService.GetPeakRatingAsync(playerInfo.Id, screeningRequest.Ruleset);
Can be defined all the way at the bottom where it is actually used. Sticking it above all of these return cases is redundant.

2024-04-04 03:27 UTC, myssto commented on API/Services/Implementations/ScreeningService.cs
> +        ScreeningResult result = ScreeningResult.Pass;
Can remove all of the following `result = ScreeningResult.Fail;` declarations if this is initially `ScreeningResult.Fail`. Before returning, check if `failReason` is not null, and if false set `result` to `ScreeningResult.Pass`.

2024-04-04 03:27 UTC, myssto commented on API/Services/Interfaces/IPlayerStatsService.cs
> +    /// <returns></returns>
Remove `<param>` and `<returns>` tags if you do not plan to document them

2024-04-04 03:27 UTC, myssto commented on API/Enums/ScreeningResult.cs
> +    /// The player passed screening
```suggestion
    /// Indicates the player passed screening
```
Similar for below

2024-04-04 03:27 UTC, myssto commented on API/Enums/ScreeningFailReason.cs
> +    /// This player does not have a rating / profile in our system
```suggestion
    /// The player does not have a rating / profile in the o!TR database
```

2024-04-04 03:27 UTC, myssto commented on API/DTOs/ScreeningRequestDTO.cs
> +    /// Whether to consider players that currently have a provisional rating
```suggestion
    /// Whether to screen players that currently have a provisional rating
```

2024-04-04 03:27 UTC, myssto commented on API/Controllers/ScreeningController.cs
> +    /// <returns></returns>
Remove empty `<returns>` tag

2024-04-10 09:40 UTC, myssto submitted a review, later dismissed
LGTM

2024-04-10 13:25 UTC, merged