Update TournamentsRepository.cs
osu-tournament-rating/otr-api pull request #273
Opened 2024-04-26 03:37 UTC by foxtail286

Closes #263, hopefully. 🤞

2024-04-26 03:38 UTC, foxtail286 commented
whoopsies, forgot to title the pull request :o

2024-04-26 03:42 UTC, hburn7 requested changes

2024-04-26 03:42 UTC, hburn7 commented on API/Repositories/Implementations/TournamentsRepository.cs
> +        return nameSearchResult.Union(abbreviationSearchResult);
This is making two round trips when we don't need to. Let's combine these into something like this:
```cs
return await _context.Tournaments.Where(x => *ILike for name* || *ILike for abbreviation*);```

2024-04-26 03:44 UTC, foxtail286 commented
Thanks for being patient, at least.

2024-04-26 04:31 UTC, hburn7 commented
Needs testing before merge, @myssto if you can.

2024-04-26 05:22 UTC, myssto commented
will test

2024-04-27 20:09 UTC, hburn7 commented
Tested locally, seems fine.

2024-04-27 20:09 UTC, merged