Implement user settings
osu-tournament-rating/otr-api pull request #311
Opened 2024-05-12 10:44 UTC by myssto

Adds a `UserSettings` entity that will hold user controllable settings for `otr-web` going forward. Currently holds two values, `Ruleset DefaultRuleset` and `bool DefaultRulesetIsControlled`. The rationale is that by default, users will have their preferred ruleset synced with the ruleset they have selected on their osu! profile. If they wish to have a different preferred ruleset for otr, they can change it, and the value will no longer sync with their osu! profile.

UserSettings are populated with defaults via a migration. By default, all users' rulesets will be set to and synced with the one selected on their osu! profile.

# New Endpoints
- `POST` `/me/settings/ruleset`
  - Updates the ruleset for the currently logged in user
  - Takes a request body of Ruleset
  - Example (Updates user ruleset to `Ruleset.Catch`)
    ```js
    fetch("otr.stagec.xyz/api/v1/me/settings/ruleset",
      {
        method: "POST",
        headers: new Headers().append("Authorization", "Bearer {}"),
        body: JSON.stringify(2),
        redirect: "follow"
      });
    ````
- `POST` `/me/settings/ruleset:sync`
  - Syncs the ruleset for the currently logged in user to their osu! profile ruleset
  - Example
    ```js
    fetch("otr.stagec.xyz/api/v1/me/settings/ruleset:sync",
      {
        method: "POST",
        headers: new Headers().append("Authorization", "Bearer {}"),
        redirect: "follow"
      });
    ````
- `POST` `/users/{id}/settings/ruleset`
  - Updates the ruleset for a user
  - Admin and owner access only
  - Takes a request body of Ruleset
  - Example (Updates ruleset to `Ruleset.Catch` for user `703` (Myssto))
    ```js
    fetch("otr.stagec.xyz/api/v1/users/703/settings/ruleset",
      {
        method: "POST",
        headers: new Headers().append("Authorization", "Bearer {}"),
        body: JSON.stringify(2),
        redirect: "follow"
      });
    ````
- `POST` `/users/{id}/settings/ruleset:sync`
  - Syncs the ruleset a user to their osu! profile ruleset
  - Example (Syncs ruleset for user `703` (Myssto))
    ```js
    fetch("otr.stagec.xyz/api/v1/users/703/settings/ruleset:sync",
      {
        method: "POST",
        headers: new Headers().append("Authorization", "Bearer {}"),
        redirect: "follow"
      });
    ````

# Schema Changes
- `UserDTO` (Returns from `GET` `/me` and `GET` `/users/{id}`)
  - Removed `ruleset`
  - Added `settings`
  - ```json
    {
    "id": 703,
    "scopes": [
        "whitelist"
    ],
    "playerId": 7470,
    "osuId": 18068913,
    "country": "US",
    "username": "rimjob",
    "settings": {
        "ruleset": 0,
        "rulesetIsControlled": false
        }
    }
    ```

Closes #286

2024-05-13 22:38 UTC, hburn7 requested changes
Have not tested locally yet, this is just a code review.

2024-05-13 22:38 UTC, hburn7 commented on API/Entities/UserSettings.cs
> +    public Ruleset? DefaultRuleset { get; set; }
nitpick, but I prefer the Created/Updated props to be on the bottom (I would even undo and recreate the migration):

From top to bottom:
- Id
- Properties
- Created
- Updated
- Navigation props / collections

2024-05-13 22:38 UTC, hburn7 commented on API/Repositories/Implementations/UserRepository.cs
> +            throw new NullReferenceException("Attempting to create a User entity without a PlayerId");
Past-tense would be better

2024-05-13 22:38 UTC, hburn7 commented on API/Services/Implementations/UserSettingsService.cs
> +        user.Settings.DefaultRuleset = user.Player.Ruleset ?? Ruleset.Standard;
I smell a nullreference here, I'd ensure user settings isn't null.

2024-05-15 12:26 UTC, hburn7 commented
Schema changes need to be implemented in web implementation before merging.

2024-05-19 00:12 UTC, myssto commented
Tested locally against otr-web#189 . Everything looks good to me.

2024-05-19 00:58 UTC, hburn7 approved these changes

2024-05-19 00:59 UTC, merged