Include ProcessingStatus & VerificationStatus in TournamentDTO
osu-tournament-rating/otr-api pull request #399
Opened 2024-09-15 15:23 UTC by hburn7

Satisfies `Expand /tournaments GET to include VerificationStatus, ProcessingStatus` portion of #371

2024-09-15 20:28 UTC, myssto requested changes

2024-09-15 20:28 UTC, myssto commented on API/DTOs/TournamentDTO.cs
> +    ///     The current state of verification
Why the extra spaces here?

2024-09-15 20:32 UTC, hburn7 commented on API/DTOs/TournamentDTO.cs
> +    ///     The current state of verification
Not sure what happened there

2024-09-16 01:52 UTC, myssto approved these changes

2024-09-16 01:59 UTC, merged