Improve processors
osu-tournament-rating/otr-api pull request #403
Opened 2024-09-15 21:25 UTC by myssto

Addresses all existing reliability and consistency concerns with the processors in the DataWorker.

- Add a Verification processor step that checks for concrete verification and rejection
- Greatly improved reliability of the `MatchHeadToHeadCheck` (TeamVs Converter)
- Use multithreading for non-blocking operations in processors
- Fix and unit test the `MatchCostCalculator`
- Unit testing for stats processors
- Support for configuring the rate limits of the `OsuClient`
- Improve the efficiency of the `OsuApiDataParserService` with caching and less redundant database interactions

2024-09-15 22:54 UTC, hburn7 requested changes

2024-09-15 22:54 UTC, hburn7 commented on DataWorkerService.Tests/Stats/GameStatsProcessorTests.cs
> +    public async void Processor_Integrated_BehavesAsExpected()
```suggestion
    public async void Processor_Integrated_ProcessesGameSuccessfully()
```

2024-09-15 22:54 UTC, hburn7 commented on DataWorkerService/Services/Implementations/OsuApiDataParserService.cs
> +        var eApiPlayers = apiPlayers.ToList();
`eApiPlayers` is a really ugly var name

2024-09-15 22:54 UTC, hburn7 commented on DataWorkerService/Services/Implementations/OsuApiDataParserService.cs
> +        var eGames = apiGames.ToList();
ew

2024-09-15 22:54 UTC, hburn7 commented on DataWorkerService/Utilities/MatchCostCalculator.cs
> +        var zScores = eGames
var name

2024-09-15 22:55 UTC, myssto commented on DataWorkerService/Services/Implementations/OsuApiDataParserService.cs
> +        var eGames = apiGames.ToList();
youre ew

2024-09-16 01:57 UTC, hburn7 approved these changes

2024-09-16 01:57 UTC, merged