Tournament verification query param
osu-tournament-rating/otr-api pull request #405
Opened 2024-09-16 01:54 UTC by hburn7

Closes #400 

If `unfiltered=true` is specified, all child navigations are returned as defined in `TournamentsBaseQuery()`. If `unfiltered=false` is specified, returns all child navigations with verified data.

2024-09-18 02:36 UTC, alixdotsh approved these changes
everything looks good on here. i think the only thing that was questionable was some of the formatting changes but i assume its IDE auto formatting or `.editorconfig`

2024-09-18 10:37 UTC, myssto requested changes

2024-09-18 10:37 UTC, myssto commented on Database/Repositories/Implementations/TournamentsRepository.cs
> +            .ThenInclude(g => g.Scores.Where(gs => gs.VerificationStatus == VerificationStatus.Verified))
This should probably also filter for processing status

2024-09-19 06:07 UTC, myssto approved these changes

2024-09-19 14:21 UTC, merged