Create PlayerHighestRanks database entity
osu-tournament-rating/otr-api pull request #410
Opened 2024-09-17 17:04 UTC by alixdotsh

Closes #372.

I believe I got it for the most part, but I probably will need to do some hefty changes. Please be blunt on the reviews.

2024-09-17 20:59 UTC, alixdotsh commented
so glad this migration worked :sob

2024-09-18 00:54 UTC, hburn7 commented
Confirmed the generated script creates a `player_highest_ranks` table with the right fields, except the `default_ruleset` table should be named `ruleset`.

2024-09-18 01:03 UTC, alixdotsh commented
lemme fix that rq

2024-09-18 01:03 UTC, hburn7 requested changes

2024-09-18 01:03 UTC, hburn7 commented on Database/Entities/PlayerHighestRanks.cs
> +    /// Global rank at the current time
```suggestion
    /// The highest global rank for this user in the given ruleset
```

2024-09-18 01:03 UTC, hburn7 commented on Database/Entities/PlayerHighestRanks.cs
> +    /// Date the global rank was achieved
```suggestion
    /// Date this player's peak global rank was achieved in the given ruleset
```

2024-09-18 01:03 UTC, hburn7 commented on Database/Entities/PlayerHighestRanks.cs
> +    /// Country rank at the current time
```suggestion
    /// The highest country rank for this user in the given ruleset
```

2024-09-18 01:03 UTC, hburn7 commented on Database/Entities/PlayerHighestRanks.cs
> +    /// Date the current country rank was achieved
```suggestion
    /// Date this player's peak country rank was achieved in the given ruleset
```

2024-09-18 01:03 UTC, hburn7 commented on Database/Entities/PlayerHighestRanks.cs
> +    // FK, required
Add a summary tag here with `The id of the player this record belongs to`

2024-09-18 01:03 UTC, hburn7 commented on Database/Entities/PlayerHighestRanks.cs
> +    public Player Player { get; set; } = null!;
Add a summary tag with `The <see cref="Player"/>` - @myssto idk if it needs to be more specific

2024-09-18 02:28 UTC, hburn7 approved these changes

2024-09-18 09:42 UTC, myssto commented on Database/Entities/PlayerHighestRanks.cs
> +    /// The highest global rank for this user in the given ruleset
You can probably remove 'in the given ruleset' from all docstrings here. Its implied by the docstring on the class itself.

2024-09-18 09:43 UTC, myssto requested changes
Lets squash the migrations on this one. This shouldn't be done in 3 separate ones. If you undo them all and recreate a new migration with the current code it should be fine.

2024-09-18 22:40 UTC, hburn7 requested changes

2024-09-18 22:40 UTC, hburn7 commented on Database/Migrations/20240918214600_PlayerHighestRanks.cs
This is an empty migration bruv

2024-09-18 22:42 UTC, alixdotsh commented on Database/Migrations/20240918214600_PlayerHighestRanks.cs
kill

2024-09-18 22:47 UTC, hburn7 commented on Database/Migrations/20240918214600_PlayerHighestRanks.cs
Fixed

2024-09-18 23:17 UTC, hburn7 commented
Have tested the current branch and can apply migrations successfully.

2024-09-18 23:18 UTC, hburn7 approved these changes

2024-09-19 06:05 UTC, myssto requested changes

2024-09-19 06:05 UTC, myssto commented on Database/Entities/PlayerHighestRanks.cs
> +    /// The highest country rank for this user
```suggestion
    /// Highest country rank achieved
```

2024-09-19 06:05 UTC, myssto commented on Database/Entities/PlayerHighestRanks.cs
> +    /// Date this player's peak country rank was achieved
```suggestion
    /// Timestamp of when the <see cref="CountryRank"/> was achieved
```

2024-09-19 06:05 UTC, myssto commented on Database/Entities/PlayerHighestRanks.cs
> +    /// The <see cref="Player"/>
```suggestion
    /// The <see cref="Player"/> this record belongs to
```

2024-09-19 06:05 UTC, myssto commented on Database/Entities/PlayerHighestRanks.cs
> +    /// The id of the player this record belongs to
```suggestion
    /// The id of the <see cref="Player"/> this record belongs to
```

2024-09-19 12:20 UTC, hburn7 commented on Database/Entities/PlayerHighestRanks.cs
> +    /// The ruleset in which this highest rank record occurred in
Would remove "in" at the end to not end sentence with preposition.

2024-09-20 21:15 UTC, myssto approved these changes

2024-09-20 21:21 UTC, merged