Player Admin Notes
osu-tournament-rating/otr-api pull request #417
Opened 2024-09-20 22:26 UTC by alixdotsh

migrations already done too, wowowow im so cool

divide and conquer. - azir

2024-09-20 22:31 UTC, hburn7 requested changes

2024-09-20 22:31 UTC, hburn7 commented on Database/Entities/PlayerAdminNote.cs
> +    public Player Player { get; set; } = null!;
Needs a player id field (`PlayerId`) with column name `player_id`. See other review comment

2024-09-20 22:31 UTC, hburn7 commented on Database/Migrations/20240920221447_PlayerAdminNote.cs
> +                    PlayerId = table.Column<int>(type: "integer", nullable: false),
Capitalization incorrect, see comment in `Database/Entities/PlayerAdminNote.cs`

2024-09-23 00:59 UTC, hburn7 approved these changes
Migrations tested and applied

2024-09-23 20:16 UTC, myssto approved these changes

2024-09-23 21:26 UTC, merged