Add `DELETE` and `GET` operations for pooled beatmaps
osu-tournament-rating/otr-api pull request #519
Opened 2024-10-26 20:29 UTC by hburn7

Depends on #518 

- Adds functionality to view all beatmaps pooled by a tournament.
- Adds functionality to delete all beatmaps pooled by a tournament.
- Adds functionality to delete specific beatmaps pooled by a tournament.

None of these operations impact the `beatmaps` table. This is strictly affecting the `__join__pooled_beatmaps` table.

2024-10-30 15:46 UTC, bugg86 approved these changes

2024-11-06 23:24 UTC, myssto requested changes
Good stuff, just some minor changes

2024-11-06 23:24 UTC, myssto commented on API/Controllers/TournamentsController.cs
> +    public async Task<IActionResult> InsertBeatmapsAsync(int id, [FromBody] ICollection<long> osuBeatmapIds)
I think it would be more appropriate to move this endpoint to the `TournamentsController.Admin.cs` partial?

2024-11-06 23:24 UTC, myssto commented on API/Controllers/TournamentsController.cs
> +        if (result is null)
```suggestion
        if (!await tournamentsService.ExistsAsync(id))
```

2024-11-06 23:24 UTC, myssto commented on API/Controllers/TournamentsController.cs
> +        if (result is null)
```suggestion
        if (!await tournamentsService.ExistsAsync(id))
```

2024-11-06 23:24 UTC, myssto commented on API/Controllers/TournamentsController.cs
> +    public async Task<IActionResult> DeleteBeatmapsAsync(int id, [FromBody] ICollection<int>? beatmapIds = null)
I think it would be more appropriate to move this endpoint to the `TournamentsController.Admin.cs` partial?

2024-11-06 23:24 UTC, myssto commented on API/Services/Interfaces/ITournamentsService.cs
> +    Task<ICollection<BeatmapDTO>> GetPooledBeatmapsAsync(int id);
Should document that it will return an empty collection if the tournament does not exist

2024-11-06 23:24 UTC, myssto commented on API/Services/Interfaces/ITournamentsService.cs
> +    Task<ICollection<BeatmapDTO>> AddPooledBeatmapsAsync(int id, ICollection<long> osuBeatmapIds);
Should document that it will return an empty collection if the tournament does not exist

2024-11-06 23:24 UTC, myssto commented on Database/Repositories/Interfaces/ITournamentsRepository.cs
> +    Task<ICollection<Beatmap>> GetPooledBeatmapsAsync(int id);
Should document that it will return an empty collection if the tournament does not exist

2024-11-06 23:24 UTC, myssto commented on Database/Repositories/Interfaces/ITournamentsRepository.cs
> +    Task<ICollection<Beatmap>> AddPooledBeatmapsAsync(int id, ICollection<long> osuBeatmapIds);
Should document that it will return an empty collection if the tournament does not exist

2024-11-09 03:58 UTC, merged