Introduce `/tournaments/{id}:accept-pre-statuses`
osu-tournament-rating/otr-api pull request #521
Opened 2024-10-27 15:59 UTC by hburn7

Part of #482 

- Introduces `/tournaments/{id}:accept-pre-statuses` endpoint which marks all `pre-` verification statuses as the `verified` equivalent.

2024-10-28 15:28 UTC, myssto requested changes
Nice work :D

I think it would be more productive if the endpoint returned the tournament since it's already in memory. This way frontend can update the status' of each entity immediately instead of requiring a refresh

2024-10-28 15:28 UTC, myssto commented on API/Controllers/TournamentsController.Admin.cs
> +    [ProducesResponseType<AdminNoteDTO>(StatusCodes.Status200OK)]
bing bong nice copy paste

2024-10-28 15:30 UTC, myssto commented
Also I'm not a fan of the name `accept-pre-statuses`. It doesn't directly reference a property like `VerificationStatus` like the proposed name does. I'll leave this one up to you

2024-11-03 16:44 UTC, hburn7 commented
> Nice work :D
> 
> I think it would be more productive if the endpoint returned the tournament since it's already in memory. This way frontend can update the status' of each entity immediately instead of requiring a refresh

Note that this returns the tournament with all child navigations, but yeah I'm fine to do this until it presents a problem.

2024-11-09 04:28 UTC, merged